name: publish-2.7

on:
  push:
      branches:
      - 'coatl'
      paths:
      - '.github/workflows/publish-2.7.yml'
      - '2.7/**'
  schedule:
      - cron: '0 8 28 * *'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        image:
          - version: '2.7'
            variant: bookworm
            tags: |
              2
              2.7
              2.7.18
          - version: '2.7'
            variant: slim-bookworm
            tags: |
              2-slim
              2.7-slim
              2.7.18-slim
    with:
      image: coatldev/python
      version: ${{ matrix.image.version }}
      variant: ${{ matrix.image.variant }}
      tags: ${{ matrix.image.tags }}
      username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}