on:
  workflow_call:
    inputs:
      version:
        description: >-
          Python version to release.
        required: true
        type: string
      variant:
        description: >-
          Image variant.
        required: true
        type: string
      tags:
        description: >-
          List of tags as key-value pair attributes.
        required: false
        type: string

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/docker-build-push-multi-platform.yml@v4
    with:
      registry-image: coatldev/python
      metadata-tags: |
        ${{ inputs.tags }}
      registry-username: ${{ vars.DOCKERHUB_USERNAME }}
      build-file: ${{ inputs.version }}/${{ inputs.variant }}/Dockerfile
      build-cache-key: ${{ inputs.version }}-${{ inputs.variant }}
      build-digest-key: ${{ inputs.version }}-${{ inputs.variant }}
    secrets:
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}